/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistema;

import DAO.AlunoDao;
import DTO.Aluno;
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emanuel
 */
public class ConsultaAluno extends javax.swing.JInternalFrame {
    private void preenchaTabela(String sql){
        
         try
        {
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/psctrabalho", "root", "");
         PreparedStatement st = conn.prepareStatement(sql);
         st.execute(); // cria o vetor

         ResultSet rs = st.executeQuery();

         DefaultTableModel model =(DefaultTableModel) tblAlunos.getModel();
         
         model.setNumRows(0);

         while(rs.next())
         {
             model.addRow(new Object[] 
             { 
                //retorna os dados da tabela do BD, cada campo e um coluna.
                rs.getInt("ra"),
                rs.getString("nome"),
                rs.getString("cpf"),
                rs.getString("turma"),
                rs.getString("idade"),
                rs.getString("faltas"),
             }); 
        } 
         rs.close();
         rs.close();
        }
       catch (SQLException ex)
       {
          System.out.println("o erro foi " +ex);
        }
        
        
        
        
        
        
        
    }
    /**
     * Creates new form ConsultaCliente
     */
    public ConsultaAluno() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        jbConsultar = new javax.swing.JButton();
        jbSaircc = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta  Aluno");

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome", "CPF", "Turma", "Idade", "Faltas"
            }
        ));
        jScrollPane1.setViewportView(tblAlunos);

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jbSaircc.setText("Sair");
        jbSaircc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbConsultar)
                    .addComponent(jbSaircc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jbSaircc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setBounds(600, 225, 780, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairccActionPerformed
      this.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jbSairccActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        preenchaTabela("select * from aluno");
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbSaircc;
    private javax.swing.JTable tblAlunos;
    // End of variables declaration//GEN-END:variables
}
